modLoader="javafml" #mandatory
loaderVersion="[34,)"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="mineplunder"
version="1.1.0"
displayName="Mineplunder"
displayURL=""
updateJSONURL=""
credits=""
authors="Smileycorp"
description=""

